/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gurvir.testframeswitch;

/**
 *
 * @author gurvi
 */
public class OptionLibrary extends javax.swing.JFrame {

    /**
     * Creates new form OptionLibrary
     */
    public OptionLibrary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Frame1Text1 = new javax.swing.JTextArea();
        btnFrame1 = new javax.swing.JButton();
        decision = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Frame1Text2 = new javax.swing.JTextArea();
        btnFrameSwitch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Frame1Text1.setColumns(20);
        Frame1Text1.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        Frame1Text1.setLineWrap(true);
        Frame1Text1.setRows(5);
        Frame1Text1.setText("Do you enter the mysterious entrance (1) or go back home (2)?\n\nENTER CHOICE (1 or 2):");
        Frame1Text1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Frame1Text1);

        btnFrame1.setFont(new java.awt.Font("OCR-A BT", 0, 24)); // NOI18N
        btnFrame1.setText("Continue");
        btnFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame1ActionPerformed(evt);
            }
        });

        decision.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        decision.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Frame1Text2.setColumns(20);
        Frame1Text2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        Frame1Text2.setLineWrap(true);
        Frame1Text2.setRows(5);
        Frame1Text2.setText("You settle on visiting the library, what could go wrong?\n\nAfter entering the library, you notice there isn’t anyone there, except for one mysterious lady, presumably the librarian. She gives you a smile and you continue to browse the library. The bookshelves were dusty and covered in cobwebs. It was almost as if no one had been here for years…\n\nYou stumble upon an unusually marked book named “Unseen Alchemy”.  You try to take the book but it won’t move. Finally, you take the book from the bookshelf and start to examine it. At the back of the bookshelf against the wall where the book was, there was what looked like a keyhole. You open the peculiar book, filled with symbols resembling chemistry, unlike anything you’ve seen before. You also find a key, possibly one that fits in the keyhole. \n\nYou turn the key into the keyhole, which reveals a hidden entrance within the bookshelves.");
        Frame1Text2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(Frame1Text2);

        btnFrameSwitch.setFont(new java.awt.Font("OCR-A BT", 0, 24)); // NOI18N
        btnFrameSwitch.setText("Continue");
        btnFrameSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decision, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFrameSwitch)
                            .addComponent(btnFrame1))))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(decision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnFrameSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(btnFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(649, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(616, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame1ActionPerformed
        // TODO add your handling code here:
        
        // Declaring variables and constants
        int userDecision;
        final int OptionA = 1;
        final int OptionB = 2;
        
        // Reading user input from text field and assingning a variable to the value
        userDecision = Integer.parseInt(decision.getText());
        
        // Switch frames depending on the answer (1, 2)
        if (userDecision == OptionA) {
            dispose();
                    OptionEntrance swap = new OptionEntrance();
                        swap.setVisible(true);
        }

        else if (userDecision == OptionB) {
            dispose();
                    OptionHome2 swap = new OptionHome2();
                        swap.setVisible(true);
        }
    }//GEN-LAST:event_btnFrame1ActionPerformed

    private void btnFrameSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameSwitchActionPerformed
        // TODO add your handling code here:
        int userDecision1;

        userDecision1 = Integer.parseInt(decision.getText());

        if (userDecision1 == 1) {
            dispose();
                    OptionEntrance swap = new OptionEntrance();
                        swap.setVisible(true);
        }

        else if (userDecision1 == 2) {
            dispose();
                    OptionHome2 swap = new OptionHome2();
                        swap.setVisible(true);
        }
    }//GEN-LAST:event_btnFrameSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Frame1Text1;
    private javax.swing.JTextArea Frame1Text2;
    private javax.swing.JButton btnFrame1;
    private javax.swing.JButton btnFrameSwitch;
    private javax.swing.JTextField decision;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
